CREATE TABLE IF NOT EXISTS anotaciones (
  id SERIAL PRIMARY KEY,
  "alumnoId" INTEGER NOT NULL,
  "profesorId" INTEGER NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  descripcion TEXT NOT NULL,
  fecha DATE NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
