CREATE TABLE IF NOT EXISTS asistencias (
  id SERIAL PRIMARY KEY,
  "alumnoId" INTEGER NOT NULL,
  "cargaAcademicaId" INTEGER NOT NULL,
  fecha DATE NOT NULL,
  estado VARCHAR(20) NOT NULL CHECK (estado IN ('PRESENTE', 'AUSENTE', 'JUSTIFICADO')),
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);