CREATE TABLE IF NOT EXISTS justificativos (
  id SERIAL PRIMARY KEY,
  "asistenciaId" INTEGER NOT NULL,
  "urlCloudStorage" VARCHAR(255) NOT NULL,
  "fechaCarga" DATE NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
