CREATE TABLE IF NOT EXISTS asistencia.mensaje (
    id SERIAL PRIMARY KEY,
    "alumnoId" INTEGER NOT NULL,
    "profesorId" INTEGER NOT NULL,
    asunto TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('COMUNICACION', 'NOTIFICACION')),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
